# Change these first
owner: xnaas
repo: nitter-instances

# Add your sites here
sites:
  - name: Official
    url: https://nitter.net
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: 42l
    url: https://nitter.42l.fr
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fr.png
  - name: PussTheCat
    url: https://nitter.pussthecat.org
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: NixNet
    url: https://nitter.nixnet.services
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: Action Sack
    url: https://nitter.actionsack.com
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
    assignees:
      - xnaas

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: xnaas.github.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /nitter-instances
  logoUrl: https://raw.githubusercontent.com/zedeus/nitter/master/public/favicon-32x32.png
  name: Nitter Instances
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page monitors Nitter instances for uptime.
  navbar:
    - title: Status
      href: /nitter-instances
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
