# Change these first
owner: xnaas
repo: nitter-instances

# Add your sites here
sites:
  - name: Official
    url: https://nitter.net
  - name: 42l
    url: https://nitter.42l.fr
  - name: PussTheCat
    url: https://nitter.pussthecat.org
  - name: NixNet
    url: https://nitter.nixnet.services
  - name: Action Sack
    url: https://nitter.actionsack.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: xnaas.github.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /nitter-instances
  logoUrl: https://raw.githubusercontent.com/zedeus/nitter/master/public/favicon-32x32.png
  name: Nitter Instances
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page monitors Nitter instances for uptime.
  navbar:
    - title: Status
      href: /nitter-instances
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
